### ISSUE TITLE
Mutilple review styles

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/wp-product-review#101]
The plugin should include multiple styles for the review. We can offer 2 in Lite version and have option to get additional in the Pro. @selul @ineagu 

What say?

**Comment by ineagu** [comment]
do you mean the main review box ? we have 2 styles for widgets.

I am not sure if is doable or easy enough since this was never took into
consideration when we have developed it.

On Tue, Jun 28, 2016 at 9:57 PM, Hardeep Asrani <notifications@github.com>
wrote:

> The plugin should include multiple styles for the review. We can offer 2
> in Lite version and have option to get additional in the Pro. @selul
> <https://github.com/selul> @ineagu <https://github.com/ineagu>
>
> What say?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/wp-product-review/issues/101>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/ABw6DBXYzyvXbaCJ7_91sKYVkaKpzUB0ks5qQXy2gaJpZM4JAeS2>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by HardeepAsrani** [comment]
Should be doable. If we can't completely change it then maybe some CSS can
give it little different styling.

**Comment by ineagu** [comment]
due to the revenues of the plugin, isn't a priority at the moment, however
yes, is a good idea and we should keep this open if there is no existing
issue

On Tue, Jun 28, 2016 at 10:05 PM, Hardeep Asrani <notifications@github.com>
wrote:

> Should be doable. If we can't completely change it then maybe some CSS can
> give it little different styling.
> On 29-Jun-2016 1:34 AM, "Ionut Neagu" <notifications@github.com> wrote:
>
> > do you mean the main review box ? we have 2 styles for widgets.
> >
> > I am not sure if is doable or easy enough since this was never took into
> > consideration when we have developed it.
> >
> > On Tue, Jun 28, 2016 at 9:57 PM, Hardeep Asrani <
> notifications@github.com>
> > wrote:
> >
> > > The plugin should include multiple styles for the review. We can offer
> 2
> > > in Lite version and have option to get additional in the Pro. @selul
> > > <https://github.com/selul> @ineagu <https://github.com/ineagu>
> > >
> > > What say?
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/Codeinwp/wp-product-review/issues/101>, or mute
> the
> > > thread
> > > <
> >
> https://github.com/notifications/unsubscribe/ABw6DBXYzyvXbaCJ7_91sKYVkaKpzUB0ks5qQXy2gaJpZM4JAeS2
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Ionut Neagu
> > http://themeisle.com | http://codeinwp.com | http://ionutn.com
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/Codeinwp/wp-product-review/issues/101#issuecomment-229166068
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AChvL5yYiRnJ96bkn2n_SfGLdto8lJhqks5qQX5fgaJpZM4JAeS2
> >
> > .
>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/wp-product-review/issues/101#issuecomment-229166351>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DHp8WmDUU_ojJmhDJf8CoHX8RDOxks5qQX6ZgaJpZM4JAeS2>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by HardeepAsrani** [comment]
@selul Any we doing it or should we close?
