### ISSUE TITLE
test round 

### ISSUE THREAD

**Issue by selul** [Codeinwp/wp-product-review#155]
@contactashish13 i would need you help for testing the refactor for this plugin.
The new code is in the refactor-v2  branch and the actual production ready is in the production. 
I would name the old version `OLD`  and the new one `NEW`

1) Use  OLD and create a review.  Make sure you fill in all the fields and install the NEW one and check if the variables are preserved.
2) Check if after switch the NEW one does the review rendering ok, exactly as it was before. 
3) With the NEW installed try to change some review data, add a new review and see if all the things are working ok.
4)  Go to the options panel  on the OLD version and change some values. Switch to NEW and make sure all the things are working as before
5) Update some general settings options in the NEW and check if is working fine.

Please make sure all the above scenarios having WP_DEBUG on and latest version of WP.

**Comment by contactashish13** [comment]
@selul 

**v4.7.2 and v4.8**

1. option for good is not available
![image](https://user-images.githubusercontent.com/12953439/27780037-4de5e7da-5fe4-11e7-9bbc-0a7916210ed0.png)

2. overall rating is incorrect
old version
![image](https://user-images.githubusercontent.com/12953439/27780127-cd2a8532-5fe4-11e7-9340-5294dddac023.png)

new version
![image](https://user-images.githubusercontent.com/12953439/27780134-d8af0b44-5fe4-11e7-9aa0-e740f2d7b19c.png)

**Comment by selul** [comment]
@contactashish13 can you do a new round of testing ?

**Comment by contactashish13** [comment]
@preda-bogdan @selul the option for "good" is now available in the settings but the score calculation gives the same incorrect result as before.

**Comment by preda-bogdan** [comment]
@contactashish13 did you start from a new product review made with the old version. Because it moves the settings to a new place on first run and then serves them from there. So if you saved the review on the new version it will have the new scores. It does not update them if the new setting already exists.

I would suggest doing a new product review on the old version, activate the refactor and confirm is the same.

Then match the product you were testing with same settings as the old to confirm that that case works also.

I have tested this in my environment and it works as expected.

Please confirm.

cc: @selul

**Comment by contactashish13** [comment]
@preda-bogdan i'm not sure what you mean. Here is what I did:

1. Activated old
2. Saved some settings
3. Saved a review
3. Activated new
4. Viewed the review without saving

Is this not the right approach?

**Comment by preda-bogdan** [comment]
@contactashish13 
1. Activate old
2. Create a new post
3. Activate Product & Configure settings
4. Save review ( Check Overall rating )
5. Activate new
6. View rating w/o save ( Check Overall rating )

Then
1. Activate old
2. Check Post that had problem with Overall Review
3. Take note of existing settings set.
4. Activate new
5. Go to Post check settings and set as same as Old
6. Check Overall Rating

I am waiting for your feedback

**Comment by contactashish13** [comment]
@preda-bogdan don't you think your approach would sacrifice backward compatibility? If I as a user have configured a review and I have to do all the above things instead of just expecting it to work out of the box, would it not be bad UX?

cc @selul

**Comment by selul** [comment]
@contactashish13 we are reworking also the pro version so both of the will get released in the same time.

For compatibility issues, when using old pro and new lite, i fine if the review is showing like before and no fatal errors occurs. I'm fine if the admin review editor dont work or other settings does not get saved.  In this case we will recommend them to update the pro version also in order to fix it.

**Comment by contactashish13** [comment]
@selul are you saying this point is not valid for testing?

> Check if after switch the NEW one does the review rendering ok, exactly as it was before.

**Comment by contactashish13** [comment]
@selul just to clarify again, this is the approach I followed

1. Activated old
2. Saved some settings
3. Saved a review. The review showed a score of 8
4. Activated new
5. Viewed the review without saving. The review showed a score of 4.8

**Comment by preda-bogdan** [comment]
@contactashish13 
Settings are being moved to a new variable for storing, the way I asked you to test ensures backwards compatibility for the first time the update is being deployed.

Because you have loaded the plugin before (the new version) now you have settings saved for that post ID with malformed data.

If you create a new post on the old version it will be the same as not having the new version installed.
When you switch to the new version, it will update the post meta with new variables, porting the existing data. This ensures backwards compatibility.

If you test on existing posts you already have metadata saved for thous posts from your last activation of the new version.

There are 3 tests that would ensure a fair testing.

Either:
1. Deploy a clean install of WP, add the old plugin, create a product, update to the new version and check if the same.

2. Activate the old version, go inside the database find the post meta for the post ID, delete the wppr fields, Activate the new version, check if the same.

3. Activate the old version, create a new product, Activate the new version, check if the same.

I suggested the latter, as it seamed easier to do.

The second round of tests i have suggested was to ensure that ( if we exclude the setting back port, even on already malformed data ) with the same settings ensured the calculation is the same.

**Comment by contactashish13** [comment]
@preda-bogdan I've followed your suggestion and the scores are still wrong. I create a new post after activating the old version and then viewed it after activating the new version - I still got the score as 4.8

@selul can you please confirm you have merged the changes?

**Comment by preda-bogdan** [comment]
@contactashish13 there are no changes to be merged if you use the `refactor-v2` branch of this git repo, you have the latest version. Did you do a `git pull` for this branch?
When activated does the new version indicate `v3.0.0` inside the plugins page?

**Comment by contactashish13** [comment]
@preda-bogdan yes it shows 3.0.0. let me test it on a fresh WP install

**Comment by contactashish13** [comment]
@preda-bogdan I tried it on a fresh install and it works properly when I followed the exact steps as before.  I'm not sure why it was not working on an existing install. It might be a good idea to make it on an existing install as well. There could be an edge case.
