### ISSUE TITLE
Support ratings out of 5 instead of out of 10

### ISSUE THREAD

**Issue by rohittm** [Codeinwp/wp-product-review#252]
@selul @ineagu I have seen many customers requesting (like: https://secure.helpscout.net/conversation/533120011/156073?folderId=212390) to have a five star rating system instead of ten. Should we add this feature?

**Comment by rohittm** [comment]
Here's another: https://wordpress.org/support/topic/rating-value/

**Comment by radu-themeisle** [comment]
+1: https://secure.helpscout.net/conversation/855357065/188951?folderId=212385

@contactashish13 do you think we can add this?

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/wp-product-review/pull/414 includes support for #413 as well

Here are the key points:
- in the settings tab, you can choose to change the rating system from out of 10 to out of 5
- in the settings tab, you can use the 5 star rating system instead of the comment sliders 
- existing comments (out of 10) will also be shown as out of 5 if that's the chosen rating system

![image](https://user-images.githubusercontent.com/12953439/58960662-3fc9af00-87c5-11e9-82d7-b896241832c3.png)


@radu-themeisle can you please test this? cc @mileamadalin in case someone else can pitch in as well, that would be great.
