### ISSUE TITLE
if "manually placed" is chosen, the review is not output. only before content and after content options work

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/wp-product-review#261]
https://secure.helpscout.net/conversation/542835681/157248/

**Comment by contactashish13** [comment]
@selul I don't understand the behavior. No matter what option I choose (before, after, manual) the behavior seems to be the same as manual.

**Comment by selul** [comment]
@contactashish13 are you saying about this particular user or generally for this plugin?

**Comment by contactashish13** [comment]
the plugin in general, at least on my instance.

**Comment by selul** [comment]
@contactashish13 I'm lost here. the manual behavior is used when the user chooses to display the review using the shortcode. before, after will show them on the review single page, before or after the content. 
also, the shortcode functionality is a pro feature, so is impossible only that to work because the before/after is working for the free ones. 

Let me know your thoughts.

**Comment by contactashish13** [comment]
@selul I'm talking about the pro version. Here are the steps to reproduce the issue:

Settings: before content
- Create a post, add some content and mark it as a review
- Create a page, add some content before, paste the shortcode, add some content after
- View the page
Result: the page is displayed **without** the content of the post.

Same behavior with after content and manually placed.

**Comment by selul** [comment]
@contactashish13 i've tried to replicate and it seems to work for me, i'm missing something -> https://drive.google.com/file/d/1c3eg7Z2yDJQ5lrIxObFs1GTJa4cT_1DS/view

**Comment by contactashish13** [comment]
@selul can you please reset the access code/credentials for qsandbox so that I can try this there?

**Comment by selul** [comment]
I don't have either those, can you try http://poopy.life ? i think we are no longer using qsandbox.

**Comment by contactashish13** [comment]
@selul you can check http://drab-spider.w5.poopy.life/2017/03/09/hello-world/. Whatever value I choose, the output of the page is identical.

**Comment by selul** [comment]
yep, the page is the same because you are using the shortcod. The before/after behaviour is related to pages where the review is created, in your case -> http://drab-spider.w5.poopy.life/2018/04/02/review/

if you change before/after the review box will be added before/after the post content. In your case, as you can see the review box is missing as you have selected manually placement.

**Comment by contactashish13** [comment]
@selul okay. In that case, the behavior/documentation/interface is not intuitive.

**Comment by selul** [comment]
yep, i think we can improve the doc here
